<a href="https://colab.research.google.com/github/souravkumar182031/agriculture/blob/main/tensorflowbasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install tensorflow==1.14..0



     |████████████████████████████████| 109.3MB 89kB/s 
     |████████████████████████████████| 51kB 5.9MB/s 
     |████████████████████████████████| 491kB 36.4MB/s 
     |████████████████████████████████| 3.2MB 31.8MB/s 
ERROR: kapre 0.3.5 has requirement tensorflow>=2.0.0, but you'll have tensorflow 1.14.0 which is incompatible.
  Found existing installation: tensorflow-estimator 2.5.0
    Uninstalling tensorflow-estimator-2.5.0:
      Successfully uninstalled tensorflow-estimator-2.5.0
  Found existing installation: tensorboard 2.5.0
    Uninstalling tensorboard-2.5.0:
      Successfully uninstalled tensorboard-2.5.0
  Found existing installation: tensorflow 2.5.0
    Uninstalling tensorflow-2.5.0:
      Successfully uninstalled tensorflow-2.5.0


In [4]:
import tensorflow as tf


In [5]:
x=tf.constant(8)
print(x)

tf.Tensor(8, shape=(), dtype=int32)


In [6]:
y=tf.constant(6,shape=(4,3))
print(y)

tf.Tensor(
[[6 6 6]
 [6 6 6]
 [6 6 6]
 [6 6 6]], shape=(4, 3), dtype=int32)


In [8]:
z=tf.constant(4,dtype=tf.float32)
print(z)

tf.Tensor(4.0, shape=(), dtype=float32)


In [9]:
a=tf.eye(7)
print(a)

tf.Tensor(
[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]], shape=(7, 7), dtype=float32)


In [10]:
print(tf.compat.v1.get_variable(name='a',initializer=(3,4,5,6)))

<tf.Variable 'a:0' shape=(4,) dtype=int32, numpy=array([3, 4, 5, 6], dtype=int32)>


In [11]:
x=tf.constant([3,4,7])
y=tf.constant([2])
z=tf.constant([2,2,2])
print(tf.multiply(x,y))
print(tf.multiply(x,z))


tf.Tensor([ 6  8 14], shape=(3,), dtype=int32)
tf.Tensor([ 6  8 14], shape=(3,), dtype=int32)
